name: OTECommandHandler
version: 1.0
description: Handles commands

author: Justin A
website: 

main: devihaka.plugins.OTECommandHandler.OTECommandHandler

commands:
   /ticket:
      description: OTE Admin Ticket System
      usage: //ticket new
      permission: 
      permission-message: 