name: OTECommandHandler
version: 1.0
description: Handles commands

author: Justin A
website: 

main: devihaka.plugins.OTECommandHandler.OTECommandHandler

commands:
   /ticket:
      description: OTE Admin Ticket System
      usage: //ticket help
      permission: 
      permission-message: 

   /issue:
      description: OTE Admin Ticket System
      usage: //issue help
      permission: 
      permission-message: 


   /service:
      description: OTE Global Service System
      usage: //service help
      permission: 
      permission-message: 
